### PR TITLE
Add Data via Webhook

### LINKED ISSUE #280: [FEATURE] GitHub events to come in via web hook
### ⭐ Suggestion

The GitHub Action to send events to our EddieHub API is not working well with forks.

I just remembered that this might be done better with GitHub webhooks
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads

### 💻 Use Cases

_No response_

### ❌ Related Problems

_No response_

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #280

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/api/pull/281"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Great work 👍

**Comment by eddiejaoude** [comment]
Testing web sockets!

**Comment by eddiejaoude** [comment]
test

**Comment by Cahllagerfeld** [comment]
test comment

**Pull request merged**
