### PR TITLE
#312: Add pagination to the `github/{id}/events` endpoint

### LINKED ISSUE #312: Add Pagination to `/github/{id}/events`
### 🙁 Actual behavior

The current payload takes too long to load, because it returns all elements

### 🙂 Expected behaviour

We should have them paginated, so the response is much faster

### 🔢 Steps to Reproduce the Problem

_No response_

### PR DESCRIPTION
**Pull request by pacyL2K19**
## Fixes Issue

Closes #312

## Changes proposed

Added pagination feature, added a `UtilsModule` for shared logic, currently with a simple pagination service file, can be extended with complex shared logic in the future

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by pacyL2K19** [comment]
@eddiejaoude please have a look
Looking forward to getting feedback from you and contributing more on the project

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thanks for contributing!

I don't think changes to the lock file are required?

**Comment by pacyL2K19** [comment]
> Thanks for contributing!
> 
> I don't think changes to the lock file are required?

They weren't required
My bad, the change came after an `npm install` I can revert it

**Comment by pacyL2K19** [comment]
> Thanks for contributing!
> 
> I don't think changes to the lock file are required?

I just checked, don't you think it's fine to let it match the version we have in the `package.json` file?
This auto updated when I ran the install command, please let me know if I should revert this change or keep the old version
@eddiejaoude

**Comment by eddiejaoude** [comment]
After merging the versions will be updated. Unless making changes to the `package.json` file, we must use `npm ci` so it uses the `lock` file and doesn't update it

**Pull request merged**
