### PR TITLE
Add Discord Module

### LINKED ISSUE #218: Migrate Discord-Module to MongoDB

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #218 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/api/pull/233"></a>

### CODE REVIEW

**Review by krishguptadev — CHANGES_REQUESTED** [review]
All good! But can you fix the lining errors?

**Comment by Cahllagerfeld** [comment]
May close this due to discussion [see here](https://github.com/EddieHubCommunity/api/discussions/224#discussioncomment-1674416) as discord module get restructured completely.

**Comment by krishguptadev** [comment]
> May close this due to discussion [see here](https://github.com/EddieHubCommunity/api/discussions/224#discussioncomment-1674416) as discord module get restructured completely.

Cool! Lemme know if there are any contribution opportunities for this!

**Comment by Cahllagerfeld** [comment]
closed for now due to #224

**Pull request closed without merging**
