### PR TITLE
fix: tests for local+astradb (#138)

### LINKED ISSUE #138: read versionnumber directly from env
we could use `process.env.npm_package_version` instead of reading the version-number with the config-serivce and the env-variables like [here](https://github.com/EddieHubCommunity/api/blob/9813ac19d735da63fa93ceb36e0ffa74b3a76031/src/app.service.ts#L10).

### LINKED ISSUE #145: Run tests against local or remote
Ideally local is better, but some people cannot run Docker locally

### LINKED ISSUE #147: Error Handling for 500
There are several issues regarding error-handling.
These need to be found with failing e2e-tests and then handled by try-catch

### PR DESCRIPTION
**Pull request by eddiejaoude**
closes #147 
closes #145

### CODE REVIEW

**Comment by eddiejaoude** [comment]
@Cahllagerfeld I tried to put you as co-author on the last commit, as I used your patch. Not sure if it worked though

**Comment by eddiejaoude** [comment]
Hmm those tests pass locally 🤔 @Cahllagerfeld could you run them locally and see what you get?

**Comment by Cahllagerfeld** [comment]
> 
> 
> Hmm those tests pass locally 🤔 @Cahllagerfeld could you run them locally and see what you get?

Sure 👍

**Comment by Cahllagerfeld** [comment]
There seem to fail 5 tests, thats the same amount like yesterday when we tested on your computer. I'll take a look at the logs as well🤔

**Comment by eddiejaoude** [comment]
I think we got there 🎉 let me know what you think when you get time @Cahllagerfeld 🤓

**Review by Cahllagerfeld — APPROVED** [review]
I have 4 failing test, but all with `Error: function timed out, ensure the promise resolves within 5000 milliseconds` so it may be that my computer is under heavy load when running all tests with docker etc.. If they passed in the action and on your pc its fine I think

**Comment by eddiejaoude** [comment]
Hm interesting. What happens if you test it against the cloud? just as a comparison

**Comment by Cahllagerfeld** [comment]
> 
> 
> Hm interesting. What happens if you test it against the cloud? just as a comparison

all passed 🙏

**Comment by eddiejaoude** [comment]
ok great 👍

**Pull request merged**
