### PR TITLE
fix: improved the `.dockerignore`

### LINKED ISSUE #305: [OTHER] Improve the `.dockerignore` file to reduce the build image size
### What would you like to share?

Improve the list of ignored files to speed up the build and reduce the size

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
## Fixes Issue

closes #305 

## Changes proposed

- Added more elements to `.dockerignore` to reduce the build size 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/api/pull/306"></a>

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
LGTM 👍

**Review by krshkodes — APPROVED** [review]
Looks great Pradumna!

**Comment by ritikbanger** [comment]
One note here: Opening the same issue in other repos and adding the same ignore thing is not consider as a contribution if you are only here for Hacktoberfest.

**Review by ritikbanger — APPROVED** [review]

**Review by ritikbanger — APPROVED** [review]
One note here: Opening the same issue in other repos and adding the same ignore thing is not consider as a contribution if you are only here for Hacktoberfest.

**Comment by Pradumnasaraf** [comment]
> One note here: Opening the same issue in other repos and adding the same ignore thing is not consider as a contribution if you are only here for Hacktoberfest.

Hey, 1st check the file content inside the ignore file in all PR then comment. 
Also if anything adds value, I will 100 repo in hacktobeset, that my concern.

**Pull request merged**
