### PR TITLE
docs: Added Issue-Templates

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
clsoes #40 
This commit proposes a template for requesting features and one for reporting bugs.
Feel free to discuss or contribute on this!

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Looks great 👍 , I think it would be more consistent if the file names were lowercase

**Comment by Cahllagerfeld** [comment]
Well Im quite confused git didnt realize the change in capitalization and deleted the versions with the capital letters 😮

**Comment by eddiejaoude** [comment]
It depends on how git is configured locally, if it uses case sensitive or not, for example in `.git/config`...

```
[core]
       ignorecase = true
```

**Comment by eddiejaoude** [comment]
But no problem, I can squash the commits 🤓

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by Cahllagerfeld** [comment]
Thx! :D

**Pull request merged**
