### PR TITLE
discordService: HttpException class convention for error responses

### PR DESCRIPTION
**Pull request by ujjwal-kr**
To reduce the workaround in importing classes like "NotFoundException" or "UnauthorizedException", added the base HttpException and HttpStatus class.

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you for submitting @ujjwal-kr 👍

**Review by khattakdev — APPROVED** [review]

**Comment by khattakdev** [comment]
@ujjwal-kr Please make sure to use [conventional commits](https://www.conventionalcommits.org/)

**Comment by ujjwal-kr** [comment]
@khattakdev thanks for the reference!

**Comment by eddiejaoude** [comment]
I can squash the commits to keep the commit convention. Thank you both 👍

**Pull request merged**
