### PR TITLE
Dependency-Update & Nest v8

### LINKED ISSUE #162: Update Nestjs v8
Nestjs released a new major version with new features and deprecations. Maybe we should upgrade our dependencies to match the new version

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #162 

- [x] update dependencies
- [x] remove and update depecrated packages in files

dont merge this before #142 isnt merged

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
I think the question with this PR is, if we currently need that update or can we postpone this PR? What do you think?

**Comment by eddiejaoude** [comment]
I think it is best to be keep dependencies up to date, otherwise if we fall far behind it makes it harder to do big jumps

**Comment by Cahllagerfeld** [comment]
Ready for merge I think

**Comment by Cahllagerfeld** [comment]
Shall I close and reopen the PR, so we dont have all these merge-commits from before in the pr or is it fine?

**Comment by eddiejaoude** [comment]
Can this be updated by `main` as I think the diff contains more than it should?

**Comment by Cahllagerfeld** [comment]
What do you mean with update 😅

**Comment by eddiejaoude** [comment]
sorry bad explanation by me 🤦‍♂️ . 

Does `main` need to be merged into this branch first as this PR seems to contain other changes at the moment?

**Comment by Cahllagerfeld** [comment]
I'm not sure, I think there were new dependencies added with the last 2 PRs that haven't been into this package.json when initially open it.

Will it help close and reopen the PR?

**Comment by Cahllagerfeld** [comment]
Just tested it. When creatign a new PR things are much clearer to understand

**Comment by eddiejaoude** [comment]
ok great, thank you 👍

**Comment by Cahllagerfeld** [comment]
reopen PR to make it easier to understand.

**Pull request closed without merging**
