### PR TITLE
Updating docs

### PR DESCRIPTION
**Pull request by Swastyy**

### CODE REVIEW

**Comment by Swastyy** [comment]
> Not sure I understand the reason for these changes? This will create a include loop

I think it will support in fixing #213

**Review by krishguptadev — CHANGES_REQUESTED** [review]
I think these changes are meaningless and can be closed.

**Comment by Swastyy** [comment]
I will be updating other sections of the documentation in this branch of the repo/PR. Thanks for suggesting.

**Comment by krishguptadev** [comment]
Hey there @Swastyy 👋 Just checking in, do you need any help?

**Comment by Swastyy** [comment]
I'll sent the PR once completed.

**Pull request closed without merging**
