### PR TITLE
docs: Swagger Declaration Consistent

### LINKED ISSUE #41: Use Validatonpipe for DTOs
Nest provides the opportunity to use [Validationpipe](https://docs.nestjs.com/techniques/validation) using `class-validator` and `class-transformer`.
Maybe we should think about using this pipe fot Data-Transfer-Objects.
Feel free to discuss on this topic.

### LINKED ISSUE #71: Refactor DTOs to make them consistent
We should refactor the DTOs, so they have a consistent naming convention.
grafik

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
fixes #71 
fixes #41 
Consistent naming of DTOs
Adds Validation to DTOs

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
Im not quite sure yet how to name the SocialsDTO. Its part of the DiscordDTO, but its required as socials are nested.
What would you suggest for naming this DTO?
grafik

**Review by eddiejaoude — APPROVED** [review]
Awesome 👍

**Comment by eddiejaoude** [comment]
> Do you have any other refactorings or bugs in mind that should be fixed before doing a new feature?

Good question. I think that might be it for the moment, unless you see anything that needs doing?

**Comment by Cahllagerfeld** [comment]
> 
> 
> > Do you have any other refactorings or bugs in mind that should be fixed before doing a new feature?
> 
> Good question. I think that might be it for the moment, unless you see anything that needs doing?

I currently dont see any other issues reagarding this as well.
Should we go on with the calendar-module then?
Or do you already have some new ideas what to build?

**Comment by eddiejaoude** [comment]
Up to you. There is also logging https://github.com/EddieHubCommunity/api/issues/60

**Pull request merged**
